# AWS credentials profile for the target AWS Account where the solution needs to be deployed
awsProfile: saraht

# Github parameters
githubOwner: STABA-Company
repoName: service-workbench-on-aws
repoBranch: feature

# Email address to receive CodePipeline failure notifications and notifications for manual approval
emailForNotifications: stabadraws@gmail.com
